spring.application.name=Strain
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret = T1zJEy0kWtMKgemqPqr0AfhTKTgQ35qX1EaoGNsql04r1vego4xZbthplD5XDNI1Cz7JiL1aGVSFbedcvIoyqB
jwt.expiration = 3600000
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.thymeleaf.prefix=/thymeleaf/
spring.web.resources.chain.cache=false
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=500
spring.devtools.restart.quiet-period=200